"""second

Revision ID: a122898c78ae
Revises: 04b9e0335c43
Create Date: 2024-06-01 16:28:52.291944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a122898c78ae'
down_revision: Union[str, None] = '04b9e0335c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=True, comment='影视名称ID'),
    sa.Column('movie_name', sa.String(length=64), nullable=True, comment='影视名称'),
    sa.Column('name', sa.String(length=16), nullable=True, comment='演员名称'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('douban_id', sa.String(length=32), nullable=True, comment='豆瓣ID'),
    sa.Column('movie_name', sa.String(length=32), nullable=True, comment='影视名称'),
    sa.Column('image_url', sa.String(length=256), nullable=True, comment='图片URL'),
    sa.Column('name_id', sa.Integer(), nullable=True, comment='影视名称ID'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('hashed_password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('movie')
    op.drop_table('artist')
    # ### end Alembic commands ###
