"""third

Revision ID: e640e1a7fc11
Revises: a122898c78ae
Create Date: 2024-06-01 21:14:15.604330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e640e1a7fc11'
down_revision: Union[str, None] = 'a122898c78ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('douban_id', sa.String(length=32), nullable=True, comment='影视名称ID'))
    op.drop_column('artist', 'name_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('name_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='影视名称ID'))
    op.drop_column('artist', 'douban_id')
    # ### end Alembic commands ###
