"""add movie image type

Revision ID: fadd66f386fd
Revises: e640e1a7fc11
Create Date: 2024-06-02 02:28:28.983733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fadd66f386fd'
down_revision: Union[str, None] = 'e640e1a7fc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('image_type', sa.String(length=16), nullable=True, comment='图片类型'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'image_type')
    # ### end Alembic commands ###
